apiVersion: apps/v1
kind: Deployment
metadata:
  name: ami-assurance-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ami-assurance-app
  template:
    metadata:
      labels:
        app: ami-assurance-app
    spec:
      containers:
        - name: ami-assurance-app
          image: salimbouazizi/ami_assurance:0.0.2
          ports:
            - containerPort: 8044
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://10.109.43.161:5432/AMIdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "salim"
---
apiVersion: v1
kind: Service
metadata:
  name: ami-assurance-service
  namespace: default
spec:
  selector:
    app: ami-assurance-app
  ports:
    - port: 8044
      targetPort: 8044
      nodePort: 30007
  type: NodePort
